services:
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
        - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  rabbitmqdata: